export type GymVideo = {
  id: number;
  title: string;
  thumbnail: string;
  video: string;
  description: string;
  duration: string;
  category: string;
  client: string;
  services: string[];
};

const BASE = "https://d3uo687t366hok.cloudfront.net/videos/gym";

export const gymVideos: GymVideo[] = [
  {
    id: 1,
    title: "Before After Phone",
    thumbnail: "/images/gym-content/thumb-01.svg",
    video: `${BASE}/Before%20After%20Phone.mp4`,
    description: "Premium transformation showcase filmed for social media campaigns.",
    duration: "00:30",
    category: "Transformation",
    client: "Fitness Industry",
    services: ["Filming", "Editing", "Color Grading"],
  },
  {
    id: 2,
    title: "MF Liluah Mix Male",
    thumbnail: "/images/gym-content/thumb-02.svg",
    video: `${BASE}/MF%20Liluah%20Mix%20Male.mp4`,
    description: "Dynamic commercial edit highlighting strength and performance.",
    duration: "00:30",
    category: "Commercial",
    client: "Fitness Industry",
    services: ["Filming", "Editing", "Motion Graphics"],
  },
  {
    id: 3,
    title: "MF Trio Male",
    thumbnail: "/images/gym-content/thumb-03.svg",
    video: `${BASE}/MF%20Trio%20Male.mp4`,
    description: "Cinematic training montage for gym promotions.",
    duration: "00:30",
    category: "Commercial",
    client: "Fitness Industry",
    services: ["Filming", "Editing", "Color Grading"],
  },
  {
    id: 4,
    title: "MFH B2 #1",
    thumbnail: "/images/gym-content/thumb-04.svg",
    video: `${BASE}/MFH%20B2%20%231_1.mp4`,
    description: "Short-form campaign optimized for Instagram and Facebook.",
    duration: "00:30",
    category: "Social Media",
    client: "Fitness Industry",
    services: ["Filming", "Editing"],
  },
  {
    id: 5,
    title: "MFH B2 #2",
    thumbnail: "/images/gym-content/thumb-05.svg",
    video: `${BASE}/MFH%20B2%20%232_1.mp4`,
    description: "Commercial edit focused on branding and engagement.",
    duration: "00:30",
    category: "Commercial",
    client: "Fitness Industry",
    services: ["Filming", "Editing"],
  },
  {
    id: 6,
    title: "MFit Behala Gym Walk Through",
    thumbnail: "/images/gym-content/thumb-06.svg",
    video: `${BASE}/MFit%20Behala%20GYM%20Walk%20Through.mp4`,
    description: "Complete walkthrough showcasing facilities and ambience.",
    duration: "01:00",
    category: "Walkthrough",
    client: "Fitness Industry",
    services: ["Drone", "Filming", "Editing"],
  },
  {
    id: 7,
    title: "MFit Ram Female Review",
    thumbnail: "/images/gym-content/thumb-07.svg",
    video: `${BASE}/MFit%20Ram%20Female%20Review%20May.mp4`,
    description: "Client testimonial filmed with cinematic storytelling.",
    duration: "00:45",
    category: "Testimonial",
    client: "Fitness Industry",
    services: ["Interview", "Editing"],
  },
  {
    id: 8,
    title: "MFit Ram Male Mix",
    thumbnail: "/images/gym-content/thumb-08.svg",
    video: `${BASE}/MFit%20Ram%20Male%20Mix%20May.mp4`,
    description: "High-energy promotional reel for fitness marketing.",
    duration: "00:45",
    category: "Commercial",
    client: "Fitness Industry",
    services: ["Filming", "Editing", "Sound Design"],
  },
  {
    id: 9,
    title: "MFit Ramrajtala Male",
    thumbnail: "/images/gym-content/thumb-09.svg",
    video: `${BASE}/MFit%20Ramrajtala%20Male%201.mp4`,
    description: "Brand-focused promotional content.",
    duration: "00:30",
    category: "Commercial",
    client: "Fitness Industry",
    services: ["Filming", "Editing"],
  },
  {
    id: 10,
    title: "MFL Solo Female V2",
    thumbnail: "/images/gym-content/thumb-01.svg",
    video: `${BASE}/MFL%20Solo%20Female%20V2%20%232.mp4`,
    description: "Individual athlete-focused cinematic production.",
    duration: "00:30",
    category: "Fitness",
    client: "Fitness Industry",
    services: ["Filming", "Editing"],
  },
  {
    id: 11,
    title: "Mix Female Skulpt",
    thumbnail: "/images/gym-content/thumb-02.svg",
    video: `${BASE}/Mix%20Female%20Skulpt_f.mp4`,
    description: "Premium female fitness campaign.",
    duration: "00:30",
    category: "Campaign",
    client: "Fitness Industry",
    services: ["Filming", "Editing"],
  },
  {
    id: 12,
    title: "Skulpt LS3",
    thumbnail: "/images/gym-content/thumb-03.svg",
    video: `${BASE}/Skulpt%20LS3.mp4`,
    description: "Luxury fitness commercial.",
    duration: "00:30",
    category: "Brand Film",
    client: "Skulpt",
    services: ["Filming", "Editing", "Color Grading"],
  },
  {
    id: 13,
    title: "Skulpt X",
    thumbnail: "/images/gym-content/thumb-04.svg",
    video: `${BASE}/Skulpt%20X%20Cricketers%20%232.mp4`,
    description: "Celebrity campaign for Skulpt.",
    duration: "00:30",
    category: "Campaign",
    client: "Skulpt",
    services: ["Filming", "Editing"],
  },
  {
    id: 14,
    title: "Solo Student Female",
    thumbnail: "/images/gym-content/thumb-05.svg",
    video: `${BASE}/Solo%20Student%20Female_F.mp4`,
    description: "Fitness transformation content.",
    duration: "00:30",
    category: "Transformation",
    client: "Fitness Industry",
    services: ["Filming", "Editing"],
  },
  {
    id: 15,
    title: "TCF Landscape",
    thumbnail: "/images/gym-content/thumb-06.svg",
    video: `${BASE}/TCF%20LANDSCAPE%204K%2030FPS.mp4`,
    description: "Landscape commercial production in 4K.",
    duration: "00:30",
    category: "Commercial",
    client: "Fitness Industry",
    services: ["Drone", "Filming", "Editing"],
  },
  {
    id: 16,
    title: "TCF Reel 4K",
    thumbnail: "/images/gym-content/thumb-07.svg",
    video: `${BASE}/TCF%20Reel%204K%2030fps.mp4`,
    description: "Vertical reel optimized for social platforms.",
    duration: "00:30",
    category: "Social Media",
    client: "Fitness Industry",
    services: ["Editing", "Motion Graphics"],
  },
];